apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-project.fullname" . }}
  labels:
    app: {{ include "node-project.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ include "node-project.name" . }}
